KsoftTssaaTwilioBundle:
    resource: "@KsoftTssaaTwilioBundle/Controller/"
    type:     annotation
    prefix:   /

KsoftTssaaStoreBundle:
    resource: "@KsoftTssaaStoreBundle/Resources/config/routing.yml"
    prefix:   /

KsoftTssaaLoginBundle:
    resource: "@KsoftTssaaLoginBundle/Resources/config/routing.yml"
    prefix:    / 

#AcmeHelloBundle:
#    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
