security:
    factories: 
        - "%kernel.root_dir%/../src/Ksoft/Tssaa/WebAppBundle/Resources/config/security_factories.yml"

    firewalls:
        wsse_secured:
            pattern: ^/
            wsse: true

    providers:
        main:
            entity: { class: Ksoft\Tssaa\WebAppBundle\Entity\User, property: username }
