security:
    factories: 
        - "%kernel.root_dir%/../src/Ksoft/Tssaa/WebAppBundle/Resources/config/security_factories.yml"

    firewalls:
        wsse_secured:
            pattern: ^/
            wsse: true

    access_control:
        - { path: ^/, roles: ROLE_USER }

    providers:
        main:
            entity: { class: Ksoft\Tssaa\WebAppBundle\Entity\User, property: username }
