security:
    firewalls:
        wsse_secured:
            anonymous: ~
            pattern: ^/

    providers:
        main:
            entity: { class: Ksoft\Tssaa\WebAppBundle\Entity\User, property: username }
