security:
    firewalls:
        wsse_secured:
            pattern: ^/
            wsse: true

    providers:
        main:
            entity: { class: Ksoft\Tssaa\WebAppBundle\Entity\User, property: username }
