#!/bin/sh
# simple as balls curl based tester for tssaa web app
if [ "-h" = $1  ]
then
    echo "curlur, like the curlur of mah hur\nusage: curlur [<DOMAIN> <URI>]"
    echo " (in that order, or not at all if you please. :| "
    exit
fi

# Headers
## Content-Type
C_TYPE="application/x-www-form-urlencoded"

## Accept-Type
ACC_TYPE="application/json"

## WSSE
X_WSSE='X-WSSE: UsernameToken Username="bob", PasswordDigest="tzc+qfcU5aGCcIlNMEJosab/yJE=",
	Nonce="OTkxOTc4YWExYWM5YjM1Zg==", Created="2012-07-16T16:50:35Z"'


# HTTP Verb
#VERB="POST"
VERB="GET"

# Request Data
DATA='{"name":"boob","occupation":"doctor","command":"barf"}'

# Target URI
if [ 0 -eq $# ]
then
    TARGET="http://tssaa.nikorova.korovasoft.com/app_dev.php/login_check"
else
    DOMAIN=$1
    URI=$2
    TARGET="$DOMAIN/$URI"
fi

# File for curl output
OUTPUT="out.curlur.html"

# testing uri construction
echo "curling $TARGET"

# and now we curl
curl -i -H $C_TYPE -H $ACC_TYPE -H $X_WSSE -X $VERB -d $DATA $TARGET | tee $OUTPUT
