#!/bin/sh
# simple as balls curl based tester for tssaa web app
if [ "-h" = $1  ]
then
    echo "curlur, like the curlur of mah hur\nusage: curlur [<DOMAIN> <URI>]"
    echo " (in that order, or not at all if you please. :| "
    exit
fi

# Headers
## Content-Type
C_TYPE="application/x-www-form-urlencoded"

## Accept-Type
ACC_TYPE="application/json"

## WSSE
X_WSSE=" UsernameToken Username=\"bob\", PasswordDigest=\"lqiv6qW9Qxsh5X59pZ85MOdg/Pw\", Nonce=\"OWNhMTZjNmEzZTFjMzRmNg==\", Created=\"2012-07-16T22:18:56Z\""


# HTTP Verb
VERB="POST"
#VERB="GET"

# Request Data
DATA='{"name":"boob","occupation":"doctor","command":"barf"}'

# Target URI
TARGET="http://tssaa.nikorova.korovasoft.com/app_dev.php/get_school_by_id"

# File for curl output
OUTPUT="out.curlur.html"

# testing uri construction
echo "curling $TARGET"

# and now we curl
curl -v -i -H $C_TYPE -H $ACC_TYPE -H X-WSSE:"$X_WSSE" -X $VERB -d $DATA $TARGET | tee $OUTPUT
