services:
    ksoft.tssaa.webappbundle.listener.request:
        class: Ksoft\Tssaa\WebAppBundle\Listener\TssaaRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    ksoft.tssaa.webappbundle.listener.view:
        class: Ksoft\Tssaa\WebAppBundle\Listener\TssaaResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelResponse }
    ksoft.tssaa.webappbundle.listener.exception:
        class: Ksoft\Tssaa\WebAppBundle\Listener\TssaaExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
