services:
    ksoft.tssaa.webappbundle.listener.request:
        class: Ksoft\Tssaa\WebAppBundle\Listener\TssaaRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
