parameters:
#    ksoft_tssaa_login.example.class: Ksoft\Tssaa\LoginBundle\Example

services:
#    ksoft_tssaa_login.example:
#        class: %ksoft_tssaa_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
